### ISSUE TITLE
Permissions for MovementClient

### ISSUE THREAD

**Issue by JanMisker** [keecker/services-api#1]
I cannot get the Keecker to move.

Using the example code I got the `ProjectorClient` `setState` method working, so I can change the projector angle. In other words: I get quite far in the process.

However, when calling `goToRelative(x,y,theta)` on a `MovementClient` I get a permission error.

`
java.lang.SecurityException: Not allowed to bind to service Intent { act=com.keecker.services.navigation.ACTION_BIND_MOVEMENT_PLANNER cmp=com.keecker.services/.navigation.MovementPlannerService }
`

I am not very experienced with Android development, can someone point me in the right direction on how to add this permission to the manifest?

**Comment by cyril-L** [comment]
Hello, you are pretty close!

You should read [Permissions overview](https://developer.android.com/guide/topics/permissions/overview) from the Android website to get the proper way of handling permission.

In your case, you want to add the `com.keecker.permission.MOVEMENT` to your `AndroidManifest.xml`:
```
 <uses-permission android:name="com.keecker.permission.MOVEMENT"/>
```

You then have to grant this permission to your app. You can avoid requesting it from your app by enabling it manually in the Android preferences. If I remember correctly it is in Settings / Apps / Your App / Permissions / Others.

Use simple movements at the beginning, like turning 90°:
```
goToRelative(0.0, 0.0, 1.57)
```

If some obstacles are nearby, the obstacles avoidance algorithm will do strange things. In that case, moving Keecker with the joystick will cancel the goToRelative command. I think there was nothing in the public API allowing you to disable the obstacles avoidance, I can check for a way to do it if you need.

**Comment by JanMisker** [comment]
Thanks for the infos, I had added the `com.keecker.permission.MOVEMENT` already, but did not manually enable it. Once I did that it worked :) 

Thanks for the quick reply!
